name: group22-env  

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel=6.12.1
  - dash=2.10.0
  - dash-bootstrap-components=1.0.0
  - plotly=5.8.0 
  - tabulate=0.8.9
  - lxml=4.8.0
  - altair=4.2.0
  - geopandas=0.11.1
  - pandas=1.5.3
  - nbformat=5.1.3  
  - pip
  - pip:
      - dash-vega-components==0.1.0
