name: group22-env

channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel=6.12.1
  - dash=2.18*
  - dash-bootstrap-components=1.7.*
  - plotly=5.8.0
  - tabulate=0.8.9
  - lxml=4.8.0
  - altair=5.5.*
  - pandas=2.2.*
  - geopandas=1.0.*
  - pip
  - numpy=1.26
  - pip:
      - dash-vega-components==0.11.*
      - gunicorn==21.2.*